COOKIE_NAMES = {
    "_ga": "Google Analitics long-term tracking of user activity.",
    "_gid": "Google Analitics short-term tracking of user activity.",
    "_gcl*": "Google Analitics, tracks ad clicks. Directly linked to advertising and profiling.",
    "_dc_gtm": "Google Analitics marketing and cross-site tracking.",
    "_gac": "Google Analitics. Stores Google Ads data when a user clicks an ad.",
    "_gali": "Google Analitics. Tracks which link the user clicked on a page.",
    "_gcl": "Google Ads. Marketing and profiling. Strong behavioural tracking.",
    "IDE": "Google Ads. Tracks users across websites to deliver targeted ads.",
    "DSID": "Google Ads. Links activity across devices and services.",
    "_fbp": "Facebook tracking. Identifies visitors for Facebook ads and retargeting.",
    "fr": "Facebook tracking. Delivers personalised ads and identifies users.",
    "_fbc": "Facebook tracking. Stores ad click info. Links ad clicks to user actions.",
    "MUID": "Microsoft tracking. Advertising and profiling. Identifies users across Microsoft services and partner sites.",
    "_uetsid": "Microsoft tracking. Marketing analytics.",
    "_uetvid": "Microsoft tracking. Long-term visitor tracking.",
    "li_gc": "LinkedIn analytics and ad tracking.",
    "lidc": "Linkedin analytics and ad tracking.",
    "personalization_id": "X tracking. Ad personalisation and tracking. Used for behavioural advertising.",
    "_hjSession": "Hotjar tracking. Very detailed behavioural monitoring, mouse movements, clicks.",
    "SRM_B": "Microsoft tracking. Ad targeting and user profiling.",
    "guest_id": "X tracking. Behaviour analysis and ad targeting.",
    "datr": "Facebook tracking. Strong behavioural and device profiling. Identify users even if they are not logged in.",
}
