# COOKIE_NAMES = {
#     "_ga": "Google Analitics long-term tracking of user activity.",
#     "_gid": "Google Analitics short-term tracking of user activity.",
#     "_gcl*": "Google Analitics, tracks ad clicks. Directly linked to advertising and profiling.",
#     "_dc_gtm": "Google Analitics marketing and cross-site tracking.",
#     "_gac": "Google Analitics. Stores Google Ads data when a user clicks an ad.",
#     "_gali": "Google Analitics. Tracks which link the user clicked on a page.",
#     "_gcl": "Google Ads. Marketing and profiling. Strong behavioural tracking.",
#     "IDE": "Google Ads. Tracks users across websites to deliver targeted ads.",
#     "DSID": "Google Ads. Links activity across devices and services.",
#     "_fbp": "Facebook tracking. Identifies visitors for Facebook ads and retargeting.",
#     "fr": "Facebook tracking. Delivers personalised ads and identifies users.",
#     "_fbc": "Facebook tracking. Stores ad click info. Links ad clicks to user actions.",
#     "MUID": "Microsoft tracking. Advertising and profiling. Identifies users across Microsoft services and partner sites.",
#     "_uetsid": "Microsoft tracking. Marketing analytics.",
#     "_uetvid": "Microsoft tracking. Long-term visitor tracking.",
#     "li_gc": "LinkedIn analytics and ad tracking.",
#     "lidc": "Linkedin analytics and ad tracking.",
#     "personalization_id": "X tracking. Ad personalisation and tracking. Used for behavioural advertising.",
#     "_hjSession": "Hotjar tracking. Very detailed behavioural monitoring, mouse movements, clicks.",
#     "SRM_B": "Microsoft tracking. Ad targeting and user profiling.",
#     "guest_id": "X tracking. Behaviour analysis and ad targeting.",
#     "datr": "Facebook tracking. Strong behavioural and device profiling. Identify users even if they are not logged in.",
# }

COOKIE_NAMES = {
    "_ga": {"description": "Google Analitics long-term tracking of user activity.", "score": 5, "severity": "Medium"},
    "_gid": {"description": "Google Analitics short-term tracking of user activity.", "score": 4, "severity": "Medium"},
    "_gcl*": {"description": "Google Analitics, tracks ad clicks. Directly linked to advertising and profiling.", "score": 7, "severity": "high"},
    "_dc_gtm": {"description": "Google Analitics marketing and cross-site tracking.", "score": 7, "severity": "high"},
    "_gac": {"description": "Google Analitics. Stores Google Ads data when a user clicks an ad.", "score": 7, "severity": "high"},
    "_gali": {"description": "Google Analitics. Tracks which link the user clicked on a page.", "score": 4, "severity": "Medium"},
    "_gcl": {"description": "Google Ads. Marketing and profiling. Strong behavioural tracking.", "score": 8, "severity": "Critical"},
    "IDE": {"description": "Google Ads. Tracks users across websites to deliver targeted ads.", "score": 9, "severity": "Critical"},
    "DSID": {"description": "Google Ads. Links activity across devices and services.", "score": 9, "severity": "Critical"},
    "_fbp": {"description": "Facebook tracking. Stores ad click info. Links ad clicks to user actions.", "score": 9, "severity": "Critical"},
    "fr": {"description": "Facebook tracking. Delivers personalised ads and identifies users.", "score": 9, "severity": "Critical"},
    "_fbc": {"description": "Google Analitics long-term tracking of user activity.", "score": 8, "severity": "Critical"},
    "MUID": {"description": "Microsoft tracking. Advertising and profiling. Identifies users across Microsoft services and partner sites.", "score": 8, "severity": "Critical"},
    "_uetsid": {"description": "Microsoft tracking. Marketing analytics.", "score": 7, "severity": "high"},
    "_uetvid": {"description": "Microsoft tracking. Long-term visitor tracking.", "score": 7, "severity": "high"},
    "li_gc": {"description": "LinkedIn analytics and ad tracking.", "score": 7, "severity": "high"},
    "lidc": {"description": "Linkedin analytics and ad tracking.", "score": 7, "severity": "high"},
    "personalization_id": {"description": "X tracking. Ad personalisation and tracking. Used for behavioural advertising.", "score": 9, "severity": "Critical"},
    "_hjSession": {"description": "Hotjar tracking. Very detailed behavioural monitoring, mouse movements, clicks.", "score": 8, "severity": "high"},
    "SRM_B": {"description": "Microsoft tracking. Ad targeting and user profiling.", "score": 9, "severity": "Critical"},
    "guest_id": {"description": "X tracking. Behaviour analysis and ad targeting.", "score": 9, "severity": "Critical"},
    "datr": {"description": "Facebook tracking. Strong behavioural and device profiling. Identify users even if they are not logged in.", "score": 9, "Critical": "high"},
}
